### ISSUE TITLE
Refine Repo Migration

### ISSUE THREAD

**Issue by simonsmh** [RikkaApps/FCM-for-Mojo-Server#2]
原有项目的配置说明(Readme.md)和服务端相关的信息是否应当迁移到这里呢？
#1

**Comment by haruue** [comment]
文档太分散了会不会给用户一种乱的感觉呢？
本来的考虑是这里只用于分发以及 Server 端的 Issue 以及 PR 。
对于用户（尤其是非开发者用户）来说，把文档移动到这里来会不会反而成为一种麻烦呢？

**Comment by simonsmh** [comment]
所以说，把所有非ffm 客户端app的信息全部分流在这里同样也是不错的选择吧。
我了解了。
